### ISSUE TITLE
Issue while installking indy-sdk on WINDOWS

### ISSUE THREAD

**Issue by harshal619** [hyperledger/indy-sdk#1021]
Hi,

I am facing Linking error while installing indy-sdk on windows system using following url:
https://www.npmjs.com/package/indy-sdk

I have installed following pre-requisites:
1. C++ Build tools
2. Python 2.7

Following is the error when i try to install the sdk:

```
> node-gyp rebuild
C:\Users\h\node_modules\indy-sdk>if not defined npm_config_node_gyp (node "C:\Users\h\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\h\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  indy.cc
  win_delay_load_hook.cc
c:\users\h\middleware\node_modules\nan\nan_new.h(208): warning
C4244: 'argument': conversion from 'unsigned __int64' to 'double', possible loss of data (compiling source file ..\src\
indy.cc) [C:\Users\h\middleware\node_modules\indy-sdk\build\ind
ynodejs.vcxproj]
  ..\src\indy.cc(248): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Numbe
  r,unsigned __int64>(A0)' being compiled
          with
          [
              A0=unsigned __int64
          ]
LINK : warning LNK4044: unrecognized option '/LC:\Users\h\middl
eware\node_modules\indy-sdk.lib'; ignored [C:\Users\h\middlewar
e\node_modules\indy-sdk\build\indynodejs.vcxproj]
LINK : warning LNK4044: unrecognized option '/LC -L\Users\h\Documents\DID\HYPERLEDGER-INDY\libindy\lib\.lib'; ignore
d [C:\Users\h\middleware\node_modules\indy-sdk\build\indynodejs
.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'indy.lib' [C:\Users\h\middleware\node_modules\indy-sdk\build\indynodejs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\h\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\h\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\h\middleware\node_modules\indy-sdk
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! indy-sdk@1.6.1-beta install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the indy-sdk@1.6.1-beta install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\h\AppData\Roaming\npm-cache\_logs\2018-08-02T10_20_40_431Z-debug.log
```

BR
Harshal

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-984 ticket](https://jira.hyperledger.org/browse/IS-984) for any further discussion.
