### ISSUE TITLE
Linker issue: Providing custom LD_LIBRARY_PATH doesn't work

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/indy-sdk#1078]
Hi, I want to play with the SDK but I got stuck.

I've installed xcode, and compiled `libindy` following these instructions https://github.com/hyperledger/indy-sdk/blob/master/doc/mac-build.md. After I compile libindy in step 5, finishing with following output
```
   Compiling rust-base58 v0.0.4
    Finished dev [unoptimized + debuginfo] target(s) in 11m 12s
```
The artefacts are built in `target` subdirectory
```
~/dev/hyperledger/indy-sdk/libindy/target/debug (master):ls -l
total 1008368
drwxr-xr-x   32 patrikstas  staff       1024 Aug 18 18:16 build
drwxr-xr-x  227 patrikstas  staff       7264 Aug 18 18:20 deps
drwxr-xr-x    2 patrikstas  staff         64 Aug 18 18:16 examples
drwxr-xr-x    4 patrikstas  staff        128 Aug 18 18:19 incremental
-rw-r--r--    2 patrikstas  staff  118999112 Aug 18 18:20 libindy.a
-rw-r--r--    1 patrikstas  staff      11594 Aug 18 18:20 libindy.d
-rwxr-xr-x    2 patrikstas  staff   41140664 Aug 18 18:20 libindy.dylib
-rw-r--r--    2 patrikstas  staff   97980520 Aug 18 18:20 libindy.rlib
drwxr-xr-x    2 patrikstas  staff         64 Aug 18 18:16 native
```
So after having libindy library ready according to the step 5, I am trying to install indy-sdk NPM package.

As the artefact is not stored in `/usr/lib/local` or so, I  am explicitly specifying path to this directory the way it's specified on NPM page, by setting `LD_LIBRARY_PATH` pointing to directory containing compiled libindy libraries.
```
~/dev/hyperledger/indy-test:LD_LIBRARY_PATH="/Users/patrikstas/dev/hyperledger/indy-sdk/libindy/target/debug" npm install --save indy-sdk

> indy-sdk@1.6.1 install /Users/patrikstas/dev/hyperledger/indy-test/node_modules/indy-sdk
> node-gyp rebuild

  CXX(target) Release/obj.target/indynodejs/src/indy.o
./Release/.deps/Release/obj.target/indynodejs/src/indy.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4194304,
  ino: 8596009699,
  size: 2597,
  blocks: 8,
  atimeMs: 1534597700000,
  mtimeMs: 1534597700000,
  ctimeMs: 1534597700087.317,
  birthtimeMs: 1534597699905.6628,
  atime: 2018-08-18T13:08:20.000Z,
  mtime: 2018-08-18T13:08:20.000Z,
  ctime: 2018-08-18T13:08:20.087Z,
  birthtime: 2018-08-18T13:08:19.906Z }
  SOLINK_MODULE(target) Release/indynodejs.node
ld: library not found for -lindy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/indynodejs.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/patrikstas/.config/yarn/global/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/patrikstas/.nvm/versions/node/v8.11.3/bin/node" "/Users/patrikstas/.config/yarn/global/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patrikstas/dev/hyperledger/indy-test/node_modules/indy-sdk
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN indy-test@1.0.0 No description
npm WARN indy-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! indy-sdk@1.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the indy-sdk@1.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patrikstas/.npm/_logs/2018-08-18T13_08_20_536Z-debug.log
```
The strange thing is that it's actually looking for something called `lindy`, not `libindy`, or is it?
Out of curiousity, I've tried to rename all those libindy.*** files in target directory respectively to `lindy.***`, but without much success. 

Am I doing something wrong, or is there a problem with the package? Thanks in advance!

Edit:
Well, I see now that `-lindy` is specified for node-gyp config here https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/binding.gyp
What's `lindy` then?

**Comment by Patrik-Stas** [comment]
Well, I see now that `-lindy` is specified for node-gyp config here https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/binding.gyp
What's `lindy` then?

**Comment by farskipper** [comment]
`-lindy` is actually `-l` followed by `indy` because the cpp linker `-l` argument expects no space following it.

You shouldn't need to rename any files in the target directory. The linker will expand `indy` to look for the OS specific naming conventions. So in your case it will prefix with `lib` and postfix with `.dylib` and find `libindy.dylib`

Try nuking your `node_modules` folder and running this again without the `"`
```
LD_LIBRARY_PATH=/Users/patrikstas/dev/hyperledger/indy-sdk/libindy/target/debug npm install --save indy-sdk
```
 I  setup the build script to use `LD_LIBRARY_PATH` in a somewhat [unconventional way](https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/binding.gyp#L16) so the `"` may be messing it up.

**Comment by Patrik-Stas** [comment]
@farskipper Thank you for response Matthew. I am using bash as my shell, so the quotes are pre-processed by bash - I've gave it a shot try nevertheless, but with no success.

What turned out to be working was to actually copy libindy.* file to `/usr/local/lib`. I am now able to install indy-sdk
```
~/dev/hyperledger/indy-test: npm install --save indy-sdk

> indy-sdk@1.6.2 install /Users/patrikstas/dev/hyperledger/indy-test/node_modules/indy-sdk
> node-gyp rebuild

  CXX(target) Release/obj.target/indynodejs/src/indy.o
./Release/.deps/Release/obj.target/indynodejs/src/indy.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4194304,
  ino: 8596120058,
  size: 2597,
  blocks: 8,
  atimeMs: 1534910449000,
  mtimeMs: 1534910449000,
  ctimeMs: 1534910449159.4302,
  birthtimeMs: 1534910448988.1003,
  atime: 2018-08-22T04:00:49.000Z,
  mtime: 2018-08-22T04:00:49.000Z,
  ctime: 2018-08-22T04:00:49.159Z,
  birthtime: 2018-08-22T04:00:48.988Z }
  SOLINK_MODULE(target) Release/indynodejs.node
npm WARN indy-test@1.0.0 No description
npm WARN indy-test@1.0.0 No repository field.

+ indy-sdk@1.6.2
updated 1 package in 11.211s
```

Anyway, passing LD_LIBRARY_PATH should also work too, right? I tried to run following and your way of parsing LD_LIBRARY_PATH seems to work as expected with my input. Running command
```
>: LD_LIBRARY_PATH="/Users/patrikstas/dev/hyperledger/indy-sdk/libindy/target/debug" node -e "console.log((process.env.LD_LIBRARY_PATH || '').split(':').map(a => '-L' + a.trim()).filter(a => a != '-L').join(' '))"
```
prints
```
-L/Users/patrikstas/dev/hyperledger/indy-sdk/libindy/target/debug
```
which does indeed contains the compiled indy libraries:
```
ls  -lah /Users/patrikstas/dev/hyperledger/indy-sdk/libindy/target/debug

total 525712
drwxr-xr-x@  13 patrikstas  staff   416B Aug 22 13:35 .
drwxr-xr-x    4 patrikstas  staff   128B Aug 22 13:35 ..
-rw-r--r--    1 patrikstas  staff     0B Aug 22 13:28 .cargo-lock
drwxr-xr-x  140 patrikstas  staff   4.4K Aug 22 13:28 .fingerprint
drwxr-xr-x   32 patrikstas  staff   1.0K Aug 22 13:28 build
drwxr-xr-x  227 patrikstas  staff   7.1K Aug 22 13:35 deps
drwxr-xr-x    2 patrikstas  staff    64B Aug 22 13:28 examples
drwxr-xr-x    4 patrikstas  staff   128B Aug 22 13:32 incremental
-rw-r--r--    2 patrikstas  staff   113M Aug 22 13:35 libindy.a
-rw-r--r--    1 patrikstas  staff    11K Aug 22 13:35 libindy.d
-rwxr-xr-x    2 patrikstas  staff    39M Aug 22 13:35 libindy.dylib
-rw-r--r--    2 patrikstas  staff    93M Aug 22 13:35 libindy.rlib
drwxr-xr-x    2 patrikstas  staff    64B Aug 22 13:28 native
```

Well, my personal roadblock is removed by copying files to `/usr/local/lib`. If you, or someone would like to investigate this, I'll still be here to assist. Also, to reproduce the issue, make sure you remove indy libraries from any default library paths to (like  `/usr/local/lib` on Mac).

**Comment by Patrik-Stas** [comment]
Few points - I did a few experiments with `binding.gyp`
```
"link_settings": {
        "libraries": [
          "-L<(module_root_dir)",
          "<!(node -e 'console.log(\"-L/Users/patrikstas/dev/hyperledger/indy-sdk/libindy/target/debug\")')",
          "-lindy"
        ]
      }
```
This works.
```
"link_settings": {
        "libraries": [
          "-L<(module_root_dir)",
          "<!(LD_LIBRARY_PATH=/Users/patrikstas/dev/hyperledger/indy-sdk/libindy/target/debug node -e \"console.log((process.env.LD_LIBRARY_PATH || '').split(':').map(a => '-L' + a.trim()).filter(a => a != '-L').join(' '))\")",
          "-lindy"
        ]
      }
```
This also works. 

So I think the problem is that LD_LIBRARY_PATH is not defined in that given node context. I am not familiar with gyp, but I suppose the solution would be to have something likes this in the gyp file
```
"<!(node -e \"console.log((<@(LD_LIBRARY_PATH) || '').split(':').map(a => '-L' + a.trim()).filter(a => a != '-L').join(' '))\")",
```
and figure out way how to pass that variable to gyp-node?

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-978 ticket](https://jira.hyperledger.org/browse/IS-978) for any further discussion.
