### ISSUE TITLE
Mocking doesn't work in libvcx NodeJS wrapper

### ISSUE THREAD

**Issue by jovfer** [hyperledger/indy-sdk#2180]
There is no changes around libvcx NodeJS wrapper, but there are some difference in behavior. I also tried to use some pinned version like v1.15.0 release. It passed the CI/CD pipeline (logs below). But on the latest CI runs of various PRs the mocking seems broken. Also I can reproduce the error in my local env every time and at the top of v1.15.0 tag as well.

### Mocking of libVCX init in tests
https://github.com/hyperledger/indy-sdk/blob/v1.15.0/vcx/wrappers/node/test/helpers/utils.ts#L7-L34

### Previous normal log
Note, this log contains `calling a stub -> calling original` or `calling a stub -> already called` as expected.

```
export TS_NODE_PROJECT="./test/tsconfig.json" export NODE_ENV='test' && export RUST_LOG="info" && export RUST_BACKTRACE=full && ./node_modules/.bin/mocha --timeout 10000 -gc --expose-gc --exit --recursive --use_strict --require ts-node/register ./test/suite1/**/*.test.ts && ./node_modules/.bin/mocha --timeout 10000 -gc --expose-gc --exit --recursive --use_strict --require ts-node/register ./test/suite2/**/*.test.ts



  Connection:
calling a stub -> calling original
    create:
      ✓ success
      ✓ success: parallel (65ms)
    connect:
      ✓ success: without phone
      ✓ success: with phone
      ✓ throws: not initialized (653ms)
    sendMessage:
      ✓ success: sends message (82ms)
    signData:
(node:524) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
      ✓ success: signs data
    verifySignature
      ✓ success: verifies the signature
    serialize:
      ✓ success
      ✓ throws: not initialized
      ✓ throws: connection deleted
    deserialize:
      ✓ success
      ✓ throws: incorrect data (39ms)
    updateState:
      ✓ returns 0: not initialized
      ✓ returns 1: not connected
      ✓ returns 2: connected
      ✓ returns 4: mocked accepted
      ✓ returns 4: mocked accepted
      ✓ returns 8: redirected with message
      - returns 4: mocked accepted in parallel
    inviteDetails:
      ✓ success: with abbr
      ✓ success: without abbr
    sendPing:
      ✓ success: send ping
    sendDiscoveryFeatures:
      ✓ success: send discovery features
    redirect:
      ✓ success
    getRedirectDetails:
      ✓ success

  CredentialDef:
calling a stub -> already called
    create:
      ✓ success
    serialize:
      ✓ success
      ✓ throws: not initialized
    deserialize:
      ✓ success
      ✓ throws: incorrect data
    getCredDefId:
      ✓ success
      ✓ throws: not initialized
    paymentManager:
      ✓ exists
      getPaymentTxn:
        ✓ success
    prepareForEndorser:
      ✓ success
    updateState:
      ✓ success
```

### Current error 
Note, this log does NOT contain `calling a stub -> calling original` and/or `calling a stub -> already called`.

```
export TS_NODE_PROJECT="./test/tsconfig.json" export NODE_ENV='test' && export RUST_LOG="info" && export RUST_BACKTRACE=full && ./node_modules/.bin/mocha --timeout 10000 -gc --expose-gc --exit --recursive --use_strict --require ts-node/register ./test/suite1/**/*.test.ts && ./node_modules/.bin/mocha --timeout 10000 -gc --expose-gc --exit --recursive --use_strict --require ts-node/register ./test/suite2/**/*.test.ts



  Connection:
    create:
      ✓ success
      ✓ success: parallel (54ms)
    connect:
      ✓ success: without phone
      ✓ success: with phone
      ✓ throws: not initialized (673ms)
    sendMessage:
      ✓ success: sends message (82ms)
    signData:
(node:527) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
      ✓ success: signs data
    verifySignature
      ✓ success: verifies the signature
    serialize:
      ✓ success
      ✓ throws: not initialized
      ✓ throws: connection deleted
    deserialize:
      ✓ success
      ✓ throws: incorrect data (42ms)
    updateState:
      ✓ returns 0: not initialized
      ✓ returns 1: not connected
      ✓ returns 2: connected
      ✓ returns 4: mocked accepted
      ✓ returns 4: mocked accepted
      ✓ returns 8: redirected with message
      - returns 4: mocked accepted in parallel
    inviteDetails:
      ✓ success: with abbr
      ✓ success: without abbr
    sendPing:
      ✓ success: send ping
    sendDiscoveryFeatures:
      ✓ success: send discovery features
    redirect:
      ✓ success
    getRedirectDetails:
      ✓ success

  CredentialDef:
    1) "before all" hook

  Credential:
    2) "before all" hook

  DisclosedProof
    3) "before all" hook

  IssuerCredential:
    4) "before all" hook

  Proof:
    5) "before all" hook

  Schema:
    6) "before all" hook

  utils:
    7) "before all" hook

  Wallet:
    8) "before all" hook


  25 passing (1s)
  1 pending
  8 failing

  1) CredentialDef:
       "before all" hook:
     Error: Library already initialized
      at Object.<anonymous> (src/api/init.ts:41:11)
      at Generator.throw (<anonymous>)
      at rejected (src/api/init.ts:6:65)
```

**Comment by jovfer** [comment]
I've put a hack at the top of one of PR
https://github.com/hyperledger/indy-sdk/pull/2174/commits/849000896e9f06c2a3219f9e89bd05073b12d374

it should be reverted as soon as the appropriate solution would found

**Comment by jovfer** [comment]
@mirgee @Patrik-Stas this is the constant reason of the failed pipelines last few weeks. I'm not familiar with JS at all so I just put a hack to unblock CI/CD.

**Comment by Patrik-Stas** [comment]
@jovfer thanks for heads up, me or @mirgee will take a look on it
