### ISSUE TITLE
Unable to install indy-sdk on windows

### ISSUE THREAD

**Issue by TheArhaam** [hyperledger/indy-sdk#2228]
I'm facing an error while installing indy sdk using "npm install --save indy-sdk"

I have the prerequisites installed : C++ build tools, Python 2.7, libindy  
```
indy.obj : error LNK2001: unresolved external symbol indy_append_request_endorser [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_to_unqualified [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_build_disable_all_txn_author_agreements_request [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_issuer_rotate_credential_def_start [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_build_get_payment_sources_with_from_request [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_parse_get_payment_sources_with_from_response [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_qualify_did [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_build_auth_rules_request [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_sign_with_address [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_verify_with_address [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_issuer_rotate_credential_def_apply [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_parse_get_nym_response [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_generate_nonce [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
indy.obj : error LNK2001: unresolved external symbol indy_get_request_info [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcxproj]
C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\Release\indynodejs.node : fatal error LNK1120: 14 unresolved externals [C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk\build\indynodejs.vcx
proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\thear\AppData\Roaming\nvm\v8.17.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\thear\\AppData\\Roaming\\nvm\\v8.17.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\thear\HyperledgerProjects\test\node_modules\indy-sdk
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! indy-sdk@1.15.0-dev-1565 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the indy-sdk@1.15.0-dev-1565 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thear\AppData\Roaming\npm-cache\_logs\2020-08-18T09_12_52_252Z-debug.log
```

**Comment by TheArhaam** [comment]
Using the latest version of libindy seemed to solve the problem "https://repo.sovrin.org/windows/libindy/master/"
