### ISSUE TITLE
Problems with nodejs sample: LedgerNotFound, IndyError: 212, AnoncredsProofRejected

### ISSUE THREAD

**Issue by pstuermlinger** [hyperledger/indy-sdk#2235]
Hello,
I'm trying to get the main.js script to finish completely, but at the end I'm getting a `IndyError: AnoncredsProofRejected`.

This is what I'm doing:
```bash
~/indy/indy-sdk/samples/nodejs $  npm run ledger:start
...
Successfully built 6b1a8649145c
Successfully tagged indy_pool:latest
edb911e270dc024f194e2acfd83627cca6268d100ef89a12fcc2e770e999288b

~/indy/indy-sdk/samples/nodejs $  npm start
...
== Apply for the job with Acme - Transcript proving ==
------------------------------
"Acme" -> Create "Job-Application" Proof Request
"Acme" -> Get key for Alice did
"Acme" -> Authcrypt "Job-Application" Proof Request for Alice
"Acme" -> Send authcrypted "Job-Application" Proof Request to Alice
"Alice" -> Authdecrypt "Job-Application" Proof Request from Acme
"Alice" -> Get credentials for "Job-Application" Proof Request
"Alice" -> Get Schema from Ledger
(node:107961) UnhandledPromiseRejectionWarning: IndyError: LedgerNotFound
    at Object.callback (/home/haggis/indy/indy-sdk/samples/nodejs/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
(node:107961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:107961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# rerun
~/indy/indy-sdk/samples/nodejs $  npm start
...
== Getting Trust Anchor credentials - Faber getting Verinym  ==
------------------------------
"Faber" > Create and store in Wallet "Faber" new DID"
"Faber" > Authcrypt "Faber DID info" for "Sovrin Steward"
"Faber" > Send authcrypted "Faber DID info" to Sovrin Steward
"Sovrin Steward" > Authdecrypted "Faber DID info" from Faber
"Sovrin Steward" > Authenticate Faber by comparision of Verkeys
(node:108080) UnhandledPromiseRejectionWarning: IndyError: 212
    at Object.callback (/home/haggis/indy/indy-sdk/samples/nodejs/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
(node:108080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:108080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# rerun
~/indy/indy-sdk/samples/nodejs $  npm start
...
== Getting Transcript with Faber - Getting Transcript Credential ==
------------------------------
"Faber" -> Create "Transcript" Credential Offer for Alice
"Faber" -> Get key for Alice did
(node:108128) UnhandledPromiseRejectionWarning: IndyError: 212
    at Object.callback (/home/haggis/indy/indy-sdk/samples/nodejs/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
(node:108128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:108128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# rerun
~/indy/indy-sdk/samples/nodejs $  npm start
== Apply for the job with Acme - Transcript proving ==
------------------------------
"Acme" -> Create "Job-Application" Proof Request
"Acme" -> Get key for Alice did
"Acme" -> Authcrypt "Job-Application" Proof Request for Alice
"Acme" -> Send authcrypted "Job-Application" Proof Request to Alice
"Alice" -> Authdecrypt "Job-Application" Proof Request from Acme
"Alice" -> Get credentials for "Job-Application" Proof Request
"Alice" -> Get Schema from Ledger
(node:108181) UnhandledPromiseRejectionWarning: IndyError: LedgerNotFound
    at Object.callback (/home/haggis/indy/indy-sdk/samples/nodejs/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
(node:108181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:108181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I can't even reproduce it for this issue. As you see above, there are some repeating errors and some new ones. What's going wrong here?

I also tried rebuilding the ledger with the `--no-cache` docker flag without success.
Any ideas?

OS: Ubuntu 16.04
Node v12.18.3

**Comment by pstuermlinger** [comment]
After another ledger-rebuild with `--no-cache` I ended with the following:
```bash
~/indy/indy-sdk/samples/nodejs $  npm start
...
== Apply for the loan with Thrift - Transcript and Job-Certificate proving  ==
------------------------------
"Thrift" -> Create "Loan-Application-KYC" Proof Request
"Thrift" -> Get key for Alice did
"Thrift" -> Authcrypt "Loan-Application-KYC" Proof Request for Alice
"Thrift" -> Send authcrypted "Loan-Application-KYC" Proof Request to Alice
"Alice" -> Authdecrypt "Loan-Application-KYC" Proof Request from Thrift
"Alice" -> Get credentials for "Loan-Application-KYC" Proof Request
"Alice" -> Get Schema from Ledger
"Alice" -> Get Claim Definition from Ledger
"Alice" -> Create "Loan-Application-KYC" Proof
"Alice" -> Authcrypt "Loan-Application-KYC" Proof for Thrift
"Alice" -> Send authcrypted "Loan-Application-KYC" Proof to Thrift
"Thrift" -> Authdecrypted "Loan-Application-KYC" Proof from Alice
"Thrift" -> Get Schemas, Credential Definitions and Revocation Registries from Ledger required for Proof verifying
~~~~~~~~~~~> authdecryptedAliceApplyLoanKycProof: {"proof":{"proofs":[{"primary_proof":{"eq_proof":{"revealed_attrs":{"first_name":"1139481716457488690172217916278103335","last_name":"5321642780241790123587902456789123452","ssn":"3124141231422543541"},"a_prime":"14298588408938393031866660210505657344372216782606328835244034840390662600774439496823530469782515475974834673510862238144115393922404383978144258419074690327729747794696416325428405217405255224191581148129797699602063640670186729288041916471723100462219322757507667560446743249614055505308093255619331877988309244479214223816102339900733874001684863257096779399219967251070865606653304777730604078180862505932399373415789881359265735018365657412544107755549327020545837210429017036813743330288620240009237153074852306918980825189529029140711382571737944286802833512195168877370058285253110666467233776999110541429244","e":"4437496639958667547955989072920613563463105816983269640787880208252302425549651244412676323434622222952642645912194584054961466360446620","v":"95124688020988939517064339184036700683408119442642426236226619999708447464752997926220607778939885334506147986004973873733700228390285797091214460146176902624332492525004844428860786477324772358432182495000277888620022044075544322108115085167633186846162097580903785342774154562661060016415293721577468202402042728556391916485714264955131503177937648007189483020001946770324550808756982436698328013879520582613049463139333624282844642096608031653546791096801655896245050425549861530988492894236964340417964485056573653296203669812548316462653497266675956139447460822378852047052498330329379740982128090859831447814948772249920263931584575830337785106457832676381864623360073099915792444234881883508227205645802175126913472332513782709812778953530450912668422143990096415760789861114676706900162543234019207973606421488147592506319837556951832819406112654183987016784937282006138130968980522641053796180177681006763066936","m":{"year":"11307897640706127575250410917233321899929962365805902005524018893687726667010249455429671993206430741566388223631422771269559040765500179787517369922115292467740401823079178383701","master_secret":"5845847383225597936888132287802515541124407846643528371946294048103918756632288858147917748566997518477189055494351260405994593264302987748111000194556147682099437386060224739268","status":"11142443427091980255757531240297051173732196121744095727821045686212899059114634053919437877845250624379793648111093482596792671757754833222026740475657018581792387993760851513278","average":"13338422441844563899028097410341664438086820076699395871254261879799078043789921840901332287400578404177547771461645912149293237567865828080965320998695808270032863567661207927983","degree":"7261297597161095540269407619328422024572207065374251019597482856263780194724561486611764461873342533972737040060826913058959393769319821197604117917197357649102452450690808730942"},"m2":"146639331747538049669273952737413447526492747574423091281306764493331371535832247522087954940797464460044661732822160320888568287305731681761691288822246192664852226551623146745"},"ge_proofs":[]},"non_revoc_proof":null}],"aggregated_proof":{"c_hash":"63482943347001050890202587459362588646445895171058709217525758767348008329545","c_list":[[113,68,66,101,203,45,84,97,45,237,252,2,147,53,113,207,6,250,201,112,249,138,162,233,48,98,156,92,255,210,249,174,79,135,40,197,168,24,2,37,144,132,119,10,110,75,146,16,41,37,27,54,102,65,252,232,3,51,136,152,240,236,214,168,210,75,21,124,150,173,210,35,75,6,24,165,223,63,95,125,47,253,118,169,0,113,26,158,15,105,205,40,10,43,46,228,119,186,68,151,76,123,141,191,170,190,48,141,13,232,218,14,195,87,30,147,0,187,129,201,21,33,188,137,85,87,113,68,169,16,10,56,174,22,184,248,237,72,74,231,65,158,15,134,157,227,39,152,100,84,140,58,208,3,186,213,231,159,201,58,227,42,231,88,128,131,57,184,151,95,62,36,164,84,251,15,83,96,57,143,36,116,106,209,90,56,113,163,241,69,172,109,135,11,159,218,179,106,19,13,229,161,207,98,129,223,239,83,16,138,178,61,213,184,144,239,204,121,249,112,159,121,65,18,50,85,125,127,18,120,174,103,155,125,81,91,131,156,109,63,143,253,17,126,64,138,1,159,20,39,151,175,72,129,201,252]]}},"requested_proof":{"revealed_attrs":{"attr3_referent":{"sub_proof_index":0,"raw":"123-45-6789","encoded":"3124141231422543541"},"attr2_referent":{"sub_proof_index":0,"raw":"Garcia","encoded":"5321642780241790123587902456789123452"},"attr1_referent":{"sub_proof_index":0,"raw":"Alice","encoded":"1139481716457488690172217916278103335"}},"self_attested_attrs":{},"unrevealed_attrs":{},"predicates":{}},"identifiers":[{"schema_id":"S4Uf58ypXydtL9XZ4hcim2:2:Transcript:1.2","cred_def_id":"9x5bpJxpkonnY3BUirH4BE:3:CL:24:TAG1","rev_reg_id":null,"timestamp":null}]}
Identifiers: undefined
(node:913) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at verifierGetEntitiesFromLedger (/home/haggis/indy/indy-sdk/samples/nodejs/src/gettingStarted.js:809:32)
    at Object.run (/home/haggis/indy/indy-sdk/samples/nodejs/src/gettingStarted.js:621:71)
    at async run (/home/haggis/indy/indy-sdk/samples/nodejs/src/main.js:7:5)
(node:913) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:913) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I included a `console.log("~~~~~~~~~~~> authdecryptedAliceApplyLoanKycProof:", authdecryptedAliceApplyLoanKycProof);` at line 619 in `gettingStarted.js`. As you see, `authdecryptedAliceApplyLoanKycProof['identifiers']` exists. And yet, identifiers are undefined in method `verifierGetEntitiesFromLedger()`.

**Comment by xiaochen-nie** [comment]
Same error here, while the java sample can run without any issue, so I suppose either it is because of the nodejs wrapper or the sample code itself.

**Comment by vp13** [comment]
Above error is because of nodejs sample code(accessing authdecryptedAliceApplyLoanKycProofJson). Replace this line https://github.com/hyperledger/indy-sdk/blob/8c669cff434f5d87e7a2e2e192423c67a9df0b33/samples/nodejs/src/gettingStarted.js#L615 with

  [**, ,**authdecryptedAliceApplyLoanKycProof] = await authDecrypt(thriftWallet, thriftAliceKey, authcryptedAliceApplyLoanKycProofJson);
