### ISSUE TITLE
Indy getting-started docker image gives Syntax error

### ISSUE THREAD

**Issue by fariduca** [hyperledger/indy-sdk#2237]
Looks like the getting-started repo has some issues. One issue is that the ipython-notebook package is no longer available as it is part of jupyter now. Second, after the images are built using 'docker-compose up' when running the container there is a syntax error. I searched the web and found that it is due to python3.5 not supporting f-strings.
Here is the error:

```
>C:\...\indy-sdk\docs\getting-started> docker-compose up
Creating network "getting-started_pool_network" with driver "bridge"
Creating indy_pool ... done
Creating getting_started ... done
Attaching to indy_pool, getting_started
getting_started | Traceback (most recent call last):
getting_started |   File "/usr/local/bin/jupyter-notebook", line 7, in <module>
getting_started |     from notebook.notebookapp import main
getting_started |   File "/usr/local/lib/python3.5/dist-packages/notebook/__init__.py", line 27, in <module>
getting_started |     from .nbextensions import install_nbextension
getting_started |   File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 26, in <module>
getting_started |     from .config_manager import BaseJSONConfigManager
getting_started |   File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 14, in <module>
getting_started |     from traitlets.config import LoggingConfigurable
getting_started |   File "/usr/local/lib/python3.5/dist-packages/traitlets/__init__.py", line 3, in <module>
getting_started |     from . import traitlets
getting_started |   File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 1781
getting_started |     return repr(f'{value.__module__}.{value.__name__}')
getting_started |                                                      ^
getting_started | SyntaxError: invalid syntax
indy_pool    | 2020-10-03 18:29:22,690 CRIT Set uid to user 1000
```

**Comment by jovfer** [comment]
One of the possible reasons is some unpinned dependency (`traitlets`?)

**Comment by fariduca** [comment]
@jovfer could you please give more detail. This error occurs even after we removed both `ipython` and `ipython-notebook` and then removed one and left the other from the getting-started.dockerfile, but the same error occurs.
Here is how the getting-started.dockerfile looks without the two packages.
```
FROM ubuntu:16.04

RUN useradd -ms /bin/bash indy

# Install environment
RUN apt-get update -y && apt-get install -y \
	wget \
	python3 \
	python3-pip \
	python-setuptools \
	apt-transport-https \
	ca-certificates \
	software-properties-common

RUN apt-get install build-essential python3-dev

WORKDIR /home/indy

RUN pip3 install -U \
	pip \
	setuptools \
	jupyter \
	python3-indy==1.11.0

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
	&& add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable" \
	&& apt-get update \
	&& apt-get install -y \
	libindy=1.11.0

USER indy

EXPOSE 8888

```

**Comment by JulianNicholls** [comment]
@fariduca It seems that the problem is exactly as you describe, in that Python 3.5 doesn't support f-strings. A further problem is that Ubuntu 16.04 doesn't support Python 3.6+.

I have fixed it locally by updating `getting-started.dockerfile` to use Ubuntu 18.04 and Python 3.6, and also changing the install of `ipython-notebook` to `notebook`.

```
FROM ubuntu:18.04               <--- This line changed

RUN useradd -ms /bin/bash indy

# Install environment
RUN apt-get update -y && apt-get install -y \
	wget \
	python3.6 \            <--- this line changed
	python3-pip \
	python-setuptools \
	apt-transport-https \
	ca-certificates \
	software-properties-common

WORKDIR /home/indy

RUN pip3 install -U \
	pip \
	notebook \               <--- this line changed
        ipython==7.9 \
	setuptools \
	jupyter \
	python3-indy==1.11.0

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
    && add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable" \
    && apt-get update \
    && apt-get install -y \
    libindy=1.11.0

USER indy

EXPOSE 8888
```
