### ISSUE TITLE
An error occurs when using Anoncreds.proverDeleteCredential on Android 10

### ISSUE THREAD

**Issue by bsleecoinplug** [hyperledger/indy-sdk#2320]
Crash occurs on libindy.so when using proverDeleteCredential on Android 10.
Android 11 and Android 8 work fine.

 

2020-12-09 10:29:12.386 3607-17571/com.iitp.iitp_demo E/[Indy::deleteCredential()-304]: storeid = 6d3a0f13-d5a2-45c9-8596-5476211ed428
2020-12-09 10:29:12.386 3607-17571/com.iitp.iitp_demo E/INDY_LOG: src/api/anoncreds.rs:1260 | indy_prover_delete_credential: >>> wallet_handle: WalletHandle(3), cred_id: 0x7a7ddc2700
2020-12-09 10:29:12.386 3607-17571/com.iitp.iitp_demo E/INDY_LOG: src/api/anoncreds.rs:1278 | prepare_result: >>> Ok(())
2020-12-09 10:29:12.386 3607-17571/com.iitp.iitp_demo E/INDY_LOG: src/api/anoncreds.rs:1280 | indy_prover_delete_credential: <<< res: Success
2020-12-09 10:29:12.386 3607-10573/com.iitp.iitp_demo E/INDY_LOG: src/commands/mod.rs:126 | AnoncredsCommand command received
2020-12-09 10:29:12.387 3607-10573/com.iitp.iitp_demo E/INDY_LOG: src/commands/anoncreds/mod.rs:60 | Prover command received
2020-12-09 10:29:12.387 3607-10573/com.iitp.iitp_demo E/INDY_LOG: src/commands/anoncreds/prover.rs:210 | DeleteCredential command received
2020-12-09 10:29:12.387 3607-10573/com.iitp.iitp_demo E/INDY_LOG: src/commands/anoncreds/prover.rs:663 | delete_credential >>> wallet_handle: WalletHandle(3), cred_id: "6d3a0f13-d5a2-45c9-8596-5476211ed428"
2020-12-09 10:29:12.390 3607-10573/com.iitp.iitp_demo E/INDY_LOG: src/api/anoncreds.rs:1272 | prepare_result: >>> Ok(())
2020-12-09 10:29:12.391 3607-10573/com.iitp.iitp_demo E/INDY_LOG: src/api/anoncreds.rs:1273 | indy_prover_delete_credential:
2020-12-09 10:29:12.391 3607-10573/com.iitp.iitp_demo W/.iitp.iitp_dem: 0xebadde09 skipped times: 0
2020-12-09 10:29:12.543 17572-17572/? E/chromium: [1209/102912.543201:ERROR:elf_dynamic_array_reader.h(61)] tag not found
2020-12-09 10:29:12.543 17572-17572/? E/chromium: [1209/102912.543803:ERROR:elf_dynamic_array_reader.h(61)] tag not found
2020-12-09 10:29:12.551 3607-10573/com.iitp.iitp_demo W/.iitp.iitp_dem: 0xebadde09 skipped times: 0

--------- beginning of crash
2020-12-09 10:29:12.551 3607-10573/com.iitp.iitp_demo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1 in tid 10573 (Thread-9), pid 3607 (.iitp.iitp_demo)
2020-12-09 10:29:12.554 13496-17101/? W/System.err: java.io.IOException: Try again
2020-12-09 10:29:12.555 13496-17101/? W/System.err: at android.net.LocalSocketImpl.readba_native(Native Method)
2020-12-09 10:29:12.555 13496-17101/? W/System.err: at android.net.LocalSocketImpl.access$300(LocalSocketImpl.java:37)
2020-12-09 10:29:12.555 13496-17101/? W/System.err: at android.net.LocalSocketImpl$SocketInputStream.read(LocalSocketImpl.java:113)
2020-12-09 10:29:12.555 13496-17101/? W/System.err: at com.sec.android.app.dexonpc.service.ConnDaemonHandler$3.run(ConnDaemonHandler.java:266)
2020-12-09 10:29:12.555 13496-17101/? W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-12-09 10:29:12.555 13496-17101/? W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-12-09 10:29:12.555 13496-17101/? W/System.err: at java.lang.Thread.run(Thread.java:919)
2020-12-09 10:29:12.555 13496-17101/? D/[DOP]ConnDaemonHandler: [263:run] App start indication listening...
2020-12-09 10:29:12.583 17575-17575/? E/crash_dump64: unknown process state: t
2020-12-09 10:29:12.610 17575-17575/? I/crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
2020-12-09 10:29:12.611 1132-1132/? I//system/bin/tombstoned: received crash request for pid 10573
2020-12-09 10:29:12.612 17575-17575/? I/crash_dump64: performing dump of process 3607 (target tid = 10573)
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: Build fingerprint: 'samsung/x1qksx/x1q:10/QP1A.190711.020/G981NKSU1BTK2:user/release-keys'
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: Revision: '14'
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: ABI: 'arm64'
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: Timestamp: 2020-12-09 10:29:12+0900
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: pid: 3607, tid: 10573, name: Thread-9 >>> com.iitp.iitp_demo <<<
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: uid: 10620
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: Cause: null pointer dereference
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x0 0000000000000001 x1 0000007a83a73c94 x2 0000007a83a73c98 x3 0000000000000001
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x4 0000000000000001 x5 0000000000000000 x6 0000000000000000 x7 0000000000000001
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x8 0101010101010101 x9 81ca4305a123dbe9 x10 0000000000430000 x11 0000000000000003
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x12 0000007a83a73c18 x13 0000007a83a73c88 x14 0000000000000001 x15 0000000000000000
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x16 0000007ae70e8f38 x17 0000007b80f0aa60 x18 00000000bf8833e9 x19 0000007a942f86c0
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x20 0000000000000000 x21 00000000736c3b00 x22 0000000012fa06b8 x23 0000000000000000
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x24 0000000000000001 x25 0000000014eca4e0 x26 0000000000000002 x27 0000000012fa06e0
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: x28 0000007a83a73ca0 x29 0000007a83a73c30
2020-12-09 10:29:12.617 17575-17575/? A/DEBUG: sp 0000007a83a73c30 lr 0000007ae70cb07c pc 0000007b80f0aa70
2020-12-09 10:29:12.706 17575-17575/? A/DEBUG: backtrace:
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #00 pc 000000000007fa70 /apex/com.android.runtime/lib64/bionic/libc.so (strlen+16) (BuildId: 27147c78d1670fec7bce21c48e84eb70)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #01 pc 0000000000008078 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libjnidispatch.so (Java_com_sun_jna_Native_getStringBytes+32)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #02 pc 0000000000140350 /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #03 pc 00000000020e640c /memfd:/jit-cache (deleted) (com.sun.jna.Native.getString+76)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #04 pc 00000000020e7920 /memfd:/jit-cache (deleted) (com.sun.jna.Pointer.getString+48)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #05 pc 00000000020e6e7c /memfd:/jit-cache (deleted) (com.sun.jna.CallbackReference$DefaultCallbackProxy.convertArgument+332)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #06 pc 00000000020e5b44 /memfd:/jit-cache (deleted) (com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback+452)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #07 pc 00000000020f0a04 /memfd:/jit-cache (deleted) (com.sun.jna.CallbackReference$DefaultCallbackProxy.callback+52)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #08 pc 0000000000137334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #09 pc 0000000000145fec /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #10 pc 00000000004b04c8 /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #11 pc 00000000004b1914 /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, jobject*, _jmethodID*, std::_va_list)+424) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #12 pc 000000000038ac1c /apex/com.android.runtime/lib64/libart.so (art::JNI::CallObjectMethodV(JNIEnv*, _jobject*, _jmethodID*, std::_va_list)+628) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #13 pc 000000000036bdf8 /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::_va_list, art::Primitive::Type, art::InvokeType)+1408) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #14 pc 00000000003597c8 /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallObjectMethod(_JNIEnv*, _jobject*, _jmethodID*, ...)+144) (BuildId: f4ae470075bacbf42f0097d74fdcc5cf)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #15 pc 000000000000b118 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libjnidispatch.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #16 pc 000000000000b8b4 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libjnidispatch.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #17 pc 000000000000fbac /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libjnidispatch.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #18 pc 000000000000fefc /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libjnidispatch.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #19 pc 00000000005f7420 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #20 pc 000000000068c534 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #21 pc 000000000057f5d4 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #22 pc 00000000007829e8 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #23 pc 000000000120e628 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so (__rust_maybe_catch_panic+32)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #24 pc 00000000004df8a0 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #25 pc 00000000011e7334 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #26 pc 000000000120d928 /data/app/com.iitp.iitp_demo-dHroFPNqbP-kNbOtj3VKpQ==/lib/arm64/libindy.so
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #27 pc 00000000000e6f20 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 27147c78d1670fec7bce21c48e84eb70)
2020-12-09 10:29:12.707 17575-17575/? A/DEBUG: #28 pc 00000000000850c8 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 27147c78d1670fec7bce21c48e84eb70)
2020-12-09 10:29:12.874 1096-9247/? D/SensorService: Calling batch handle==7 flags=0 rate=200000000 timeout== 0
2020-12-09 10:29:12.874 862-917/? I/sensors-hal: batch:270, com.samsung.sensor.light_cct/7, period=200000000, max_latency=0 request completed
2020-12-09 10:29:12.874 862-917/? I/sensors-hal: activate:178, com.samsung.sensor.light_cct/7 en=1
2020-12-09 10:29:12.875 862-917/? I/sensors-hal: get_qmi_debug_flag:230, support_qmi_debug : false
2020-12-09 10:29:12.881 862-917/? I/sensors-hal: activate:196, com.samsung.sensor.light_cct/7 en=1 completed
2020-12-09 10:29:12.881 1096-9247/? D/SensorManager: registerListener :: 7, TMD4907 Light CCT Non-wakeup, 200000, 0,
2020-12-09 10:29:12.943 1132-1132/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_02
2020-12-09 10:29:12.946 1096-17581/? W/ActivityManager: crash : com.iitp.iitp_demo,0
2020-12-09 10:29:12.946 1096-17582/? I/DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
2020-12-09 10:29:12.947 1096-1420/? I/BootReceiver: Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)

**Comment by bsleecoinplug** [comment]
https://github.com/hyperledger/indy-sdk/commit/bad761804828aa286d5140645dc8648ab5a2abf6
