### ISSUE TITLE
samples/nodejs setup error | error: no matching member function for call to 'Set'

### ISSUE THREAD

**Issue by cdesch** [hyperledger/indy-sdk#2345]
In following the instructions to run the [NodeJS Sample](https://github.com/hyperledger/indy-sdk/tree/master/samples/nodejs), I get the following error

```
../src/indy.cc:234:24: error: no matching member function for call to 'Set'
                tuple->Set(0, Nan::New<v8::Number>(icb->handle0));
```

Steps to reproduce:

- Clone https://github.com/hyperledger/indy-sdk
- Run docker commands:

      docker network create --subnet 10.0.0.0/8 indy_pool_network
      docker build --build-arg pool_ip=10.0.0.2 -f ci/indy-pool.dockerfile -t indy_pool .
      docker run -d --ip="10.0.0.2" --net=indy_pool_network indy_pool

- run `npm install` in `samples/nodejs`

System Details:

- Node 14.8.0
- MacOS Mojave 10.14.6
- indy-sdk commit 7349f5684bff5eb84bc370f1c6c8fc7e8c054613

Other:

Is there a specific version of the SDK that should be used instead of pulling from the master branch?

Full Error:
```
 ! > ~/p/indy-sdk > samples/nodejs > npm install                                                                            
> indy-sdk@1.11.0 install /Users/cj1/projects/indy-sdk/samples/nodejs/node_modules/indy-sdk
> node-gyp rebuild

  CXX(target) Release/obj.target/indynodejs/src/indy.o
In file included from ../src/indy.cc:4:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:5265:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
../src/indy.cc:234:24: error: no matching member function for call to 'Set'
                tuple->Set(0, Nan::New<v8::Number>(icb->handle0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:235:24: error: no matching member function for call to 'Set'
                tuple->Set(1, Nan::New<v8::Number>(icb->u32int0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:243:24: error: no matching member function for call to 'Set'
                tuple->Set(0, toJSString(icb->str0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:244:24: error: no matching member function for call to 'Set'
                tuple->Set(1, Nan::New<v8::Number>(icb->i64int0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:252:24: error: no matching member function for call to 'Set'
                tuple->Set(0, toJSString(icb->str0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:253:24: error: no matching member function for call to 'Set'
                tuple->Set(1, Nan::NewBuffer(icb->buffer0data, icb->buffer0len).ToLocalChecked());
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:258:24: error: no matching member function for call to 'Set'
                tuple->Set(0, toJSString(icb->str0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:259:24: error: no matching member function for call to 'Set'
                tuple->Set(1, toJSString(icb->str1));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:264:24: error: no matching member function for call to 'Set'
                tuple->Set(0, toJSString(icb->str0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:265:24: error: no matching member function for call to 'Set'
                tuple->Set(1, toJSString(icb->str1));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:266:24: error: no matching member function for call to 'Set'
                tuple->Set(2, Nan::New<v8::Number>(icb->timestamp0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:271:24: error: no matching member function for call to 'Set'
                tuple->Set(0, toJSString(icb->str0));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:272:24: error: no matching member function for call to 'Set'
                tuple->Set(1, toJSString(icb->str1));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/indy.cc:273:24: error: no matching member function for call to 'Set'
                tuple->Set(2, toJSString(icb->str2));
                ~~~~~~~^~~
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cj1/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 warning and 14 errors generated.
make: *** [Release/obj.target/indynodejs/src/indy.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/14.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cj1/projects/indy-sdk/samples/nodejs/node_modules/indy-sdk
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! indy-sdk@1.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the indy-sdk@1.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cj1/.npm/_logs/2020-12-31T16_57_01_979Z-debug.log

```

**Comment by CluEleSsUK** [comment]
I have the same problem with node v15.12.0.  I tried switching to v12.22.1 and got some deprecation warnings for the Set problems, but it did build successfully.

**Comment by kukgini** [comment]
I also get the same error. How should I solve it?
