### ISSUE TITLE
Error loading libsodium using the node wrapper

### ISSUE THREAD

**Issue by CluEleSsUK** [hyperledger/indy-sdk#2383]
Currently trying to go through the node tutorials for Indy and have not gotten very far.

After downloading the latest indy dylib and installing the latest node wrapper, when trying to run the most basic demo app I get the following:
```
$ npm start

> sovrin-learning@1.0.0 start /Users/somebody/repos/sovrin-learning
> node index.js

/Users/somebody/repos/sovrin-messing/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/somebody/repos/sovrin-messing/node_modules/indy-sdk/build/Release/indynodejs.node, 1): Library not loaded: /usr/local/opt/libsodium/lib/libsodium.18.dylib
  Referenced from: /usr/local/lib/libindy.dylib
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/Users/somebody/repos/sovrin-messing/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/somebody/repos/sovrin-messing/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
```
I tried running `brew install libsodium`,  which appears to have installed version 1.18.1

However the contents of `/usr/local/opt/libsodium/lib` include files called `libsodium.23.dylib` and `libsodium.dylib`, but not the `libsodium.18.dylib` sought by the libindy dylib.
In case it's relevant, my libindy is in `/usr/local/lib` rather than `/usr/lib`, as I'm on OSX Big Sur and it has some protections against sticking stuff in `/usr/lib` by default.

MacOS 11.2.3
Node v12.22.1 (I tried 15+, but right now neither it nor 14 seem to be compatible with Indy...)
npm 6.14.12

**Comment by CluEleSsUK** [comment]
Interestingly when I stick a symbolic link with `18` in it, I get a new, but similar error:
```Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib``` - perhaps I've not installed indysdk correctly?

**Comment by CluEleSsUK** [comment]
Another small confusing note: on https://repo.sovrin.org/macos/libindy I noticed that the master versions are all 1.15.*, but both stable and rc is 1.16.* - is this intentional?

**Comment by CluEleSsUK** [comment]
Trying with the latest master (1.15.1628) and LD_LIBRARY_PATH gives me another interesting error message:

```
$ LD_LIBRARY_PATH=/Users/somebody/Downloads/libindy_1.15.0/lib npm start

> sovrin-learning@1.0.0 start /Users/somebody/repos/sovrin-learning
> node index.js

/Users/somebody/repos/sovrin-learning/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/somebody/repos/sovrin-learning/node_modules/indy-sdk/build/Release/indynodejs.node, 1): Library not loaded: /Users/jenkins/workspace/indy-sdk_indy-sdk-cd_rc/libindy/target/release/deps/libindy.dylib
  Referenced from: /Users/somebody/repos/sovrin-learning/node_modules/indy-sdk/build/Release/indynodejs.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/Users/somebody/repos/sovrin-learning/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/somebody/repos/sovrin-learning/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    ```
    
Interestingly, it's looking in `/Users/jenkins/workspace` which I'm assuming is the project CI, as I'm not called Jenkins :)

**Comment by JamesKEbert** [comment]
Some relevant troubleshooting information that I think would address some of your primary issues here over in Aries Framework Javascript: https://github.com/Indicio-tech/aries-framework-javascript/blob/main/TROUBLESHOOTING.md

I recently had to troubleshoot some issues here, so may be able to help more, and there's definitely people happy to help on the [aries-framework Rocketchat](https://chat.hyperledger.org/channel/aries-javascript).
