### ISSUE TITLE
How to fix nodejs Error Cannot find module

### ISSUE THREAD

**Issue by colinkim** [hyperledger/indy-sdk#2394]
I'm trying to "node write-did-and-query-verkey" by CLI
I have error following

module.js:550
    throw err;
    ^

Error: Cannot find module '/indy-sdk/docs/how-tos/write-did-and-query-verkey/nodejs/write-did-and-query-verkey'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

What should I do???? I don´t know how to solve it? :) thanks!

**Comment by kingworm** [comment]
what version are you using for nodejs?
