### ISSUE TITLE
docker-compose up | SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 89bitrelation-89** [hyperledger/indy-sdk#2406]
/docs/getting-started$ docker-compose up
Creating network "getting-started_pool_network" with driver "bridge"
Creating indy_pool ... done
Creating getting_started ... done
Attaching to indy_pool, getting_started
indy_pool    | 2021-06-29 17:25:17,131 CRIT Set uid to user 1000
getting_started | Traceback (most recent call last):
getting_started |   File "/usr/local/bin/jupyter-notebook", line 6, in <module>
getting_started |     from notebook.notebookapp import main
getting_started |   File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 81, in <module>
getting_started |     from .services.kernels.kernelmanager import MappingKernelManager, AsyncMappingKernelManager
getting_started |   File "/usr/local/lib/python3.5/dist-packages/notebook/services/kernels/kernelmanager.py", line 18, in <module>
getting_started |     from jupyter_client.session import Session
getting_started |   File "/usr/local/lib/python3.5/dist-packages/jupyter_client/__init__.py", line 6, in <module>
getting_started |     from .asynchronous import AsyncKernelClient  # noqa
getting_started |   File "/usr/local/lib/python3.5/dist-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
getting_started |     from .client import AsyncKernelClient  # noqa
getting_started |   File "/usr/local/lib/python3.5/dist-packages/jupyter_client/asynchronous/client.py", line 6, in <module>
getting_started |     from jupyter_client.channels import HBChannel
getting_started |   File "/usr/local/lib/python3.5/dist-packages/jupyter_client/channels.py", line 47
getting_started |     time_to_dead: float = 1.0
getting_started |                 ^
getting_started | SyntaxError: invalid syntax
getting_started exited with code 1

Does anyone faced the same?

**Comment by 89bitrelation-89** [comment]
KIndly find https://github.com/hyperledger/indy-sdk/issues/2404
