### ISSUE TITLE
build fail and lib error on mac

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/indy-sdk#2427]
Recently, I am try with indy hello world sample.
And I am try to use indy-sdk and run sample as hello world env.
But, when I run python3 src.main as below, it told me I don’t have openssl dylib…
I had installed the libsodium, which is 23 instead of 18 as where I get the indy dylib required the https://repo.sovrin.org/macos/
… so the readme file I referred in indy-sdk actually nothing help as I still need to manually install and compile a lot for libs as dependency for indy.

yuanyi@192 python % python3 -m src.main
INFO:src.getting_started:Getting started -> started
INFO:src.getting_started:Open Pool Ledger: pool1
ERROR:indy.libindy:_load_cdll: Can't load libindy: dlopen(libindy.dylib, 6): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/lib/libindy.dylib
  Reason: image not found
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yuanyi/OpenSource/indy-sdk/samples/python/src/main.py", line 18, in <module>
    run_coroutine(main)
  File "/Users/yuanyi/OpenSource/indy-sdk/samples/python/src/utils.py", line 52, in run_coroutine
    loop.run_until_complete(coroutine())
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/yuanyi/OpenSource/indy-sdk/samples/python/src/main.py", line 8, in main
    await getting_started.run()
  File "/Users/yuanyi/OpenSource/indy-sdk/samples/python/src/getting_started.py", line 68, in run
    await pool.set_protocol_version(PROTOCOL_VERSION)
  File "/usr/local/lib/python3.9/site-packages/indy/pool.py", line 212, in set_protocol_version
    res = await do_call('indy_set_protocol_version',
  File "/usr/local/lib/python3.9/site-packages/indy/libindy.py", line 30, in do_call
    err = getattr(_cdll(), name)(command_handle,
  File "/usr/local/lib/python3.9/site-packages/indy/libindy.py", line 133, in _cdll
    _cdll.cdll = _load_cdll()
  File "/usr/local/lib/python3.9/site-packages/indy/libindy.py", line 165, in _load_cdll
    raise e
  File "/usr/local/lib/python3.9/site-packages/indy/libindy.py", line 160, in _load_cdll
    res = CDLL(libindy_name)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libindy.dylib, 6): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/lib/libindy.dylib
  Reason: image not found

A yes, we have a Mac.build.sh… which reports error either...
The following warnings were emitted during compilation:

warning: build/expando.c:10:1: error: pasting formed 'RUST_VERSION_OPENSSL_(', an invalid preprocessing token
warning: VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
warning: ^
warning: build/expando.c:5:23: note: expanded from macro 'VERSION'
warning: #define VERSION(n, v) VERSION2(n, v)
warning:                       ^
warning: build/expando.c:4:43: note: expanded from macro 'VERSION2'
warning: #define VERSION2(n, v) RUST_VERSION_##n##_##v
warning:                                           ^
warning: 1 error generated.

error: failed to run custom build command for `openssl-sys v0.9.59`

Caused by:
  process didn't exit successfully: `/Users/yuanyi/OpenSource/indy-sdk/libindy/target/debug/build/openssl-sys-1bcf789585624d4c/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR
  X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
  X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_DIR
  X86_64_APPLE_DARWIN_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = /usr/local/opt/openssl@3
  cargo:rustc-link-search=native=/usr/local/opt/openssl@3/lib
  cargo:include=/usr/local/opt/openssl@3/include
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-apple-darwin")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/usr/local/opt/openssl@3/include" "-Wall" "-Wextra" "-E" "build/expando.c"
  cargo:warning=build/expando.c:10:1: error: pasting formed 'RUST_VERSION_OPENSSL_(', an invalid preprocessing token
  cargo:warning=VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
  cargo:warning=^
  cargo:warning=build/expando.c:5:23: note: expanded from macro 'VERSION'
  cargo:warning=#define VERSION(n, v) VERSION2(n, v)
  cargo:warning=                      ^
  cargo:warning=build/expando.c:4:43: note: expanded from macro 'VERSION2'
  cargo:warning=#define VERSION2(n, v) RUST_VERSION_##n##_##v
  cargo:warning=                                          ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr
  thread 'main' panicked at '
  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"cc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-g\" \"-fno-omit-frame-pointer\" \"-m64\" \"-I\" \"/usr/local/opt/openssl@3/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel

  See rust-openssl README for more information:

      https://github.com/sfackler/rust-openssl#linux
  ', /Users/yuanyi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.59/build/main.rs:141:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: failed on line 54.

**Comment by baegjae** [comment]
I solved this issue by below command

`brew uninstall openssl@3`

**Comment by SamYuan1990** [comment]
> I solved this issue by below command
> 
> `brew uninstall openssl@3`

uninstall?

if uninstall works, I hope indy group can take a look at with this issue. Is there any conflict between indy and openssl?

**Comment by WadeBarnes** [comment]
This issue might be related to the this fix; https://github.com/hyperledger/indy-sdk/pull/2472

**Comment by baegjae** [comment]
Actually, OPENSSL_DIR should be set with the path of openssl@1.1
However, below line set with the path of openssl@3
https://github.com/hyperledger/indy-sdk/blob/eb7c7e2a41d427ae5aed42c45bc516770c619279/libindy/mac.build.sh#L44

I think this line needs to be fixed.

A simple solution is to remove openssl@3.
