### ISSUE TITLE
Can't run getting-started with docker-compose: can not build jupyter service

### ISSUE THREAD

**Issue by viktor-settlemint** [hyperledger/indy-sdk#2467]
Hello team,

I have this error message when I run docker-compose up -d:

------                                                                                                                          
 > [6/7] RUN pip3 install -U    pip       ipython==7.9  setuptools      python3-indy==1.11.0:                                   
#9 0.298 Traceback (most recent call last):                                                                                     
#9 0.298   File "/usr/local/bin/pip3", line 7, in <module>                                                                      
#9 0.298     from pip._internal.cli.main import main                                                                            
#9 0.298   File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
#9 0.298     sys.stderr.write(f"ERROR: {exc}")
#9 0.298                                    ^
#9 0.298 SyntaxError: invalid syntax
------
executor failed running [/bin/sh -c pip3 install -U 	pip       ipython==7.9 	setuptools 	python3-indy==1.11.0]: exit code: 1

When I think it comes from ipython-notebook which is deprecated. 
Can you please point me what should be latest packages to install so that I can run the tutorial please?

Thanks

**Comment by tdiesler** [comment]
This is likely a duplicate of #2446
In the mean, you could try running from this branch https://github.com/tdiesler/indy-sdk/tree/next
