### ISSUE TITLE
Unable to use Libindy - Problem with OpenSSL1.0.0

### ISSUE THREAD

**Issue by nialljvs** [hyperledger/indy-sdk#2482]
```
Error: dlopen(.../aries-framework-javascript/node_modules/indy-sdk/build/Release/indynodejs.node, 0x0001): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/lib/libindy.dylib
  Reason: tried: '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (no such file), '/usr/local/lib/libssl.1.0.0.dylib' (no such file), '/usr/lib/libssl.1.0.0.dylib' (no such file)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1181:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Users/ab020sq/Development/JavaScript/aries-framework-javascript/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/ab020sq/Development/JavaScript/aries-framework-javascript/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  code: 'ERR_DLOPEN_FAILED'
}
error Command failed with exit code 1.
```
Problem is that OpenSSL1.0.0 no longer exists, and libindy seems to depend on it. Only workaround was to use our own custom build of Libindy which doesn't have the dependency for that particular version.
Tried the workarounds in the 'Troubleshooting' docs - but doesn't work.

The same thing happens regardless of installation (i.e. brew install, download from sovrin repo).

Using latest version - 1.16.0

Working on a Macbook Pro, Intel chip, running Monterey version 12.2.1

**Comment by zerjioang** [comment]
@nialljvs you need to find a way to install openssl 1.0.0 on your system. is a requirement that must exists
