### ISSUE TITLE
Not able to get nodes started on Mac possibly due to missing indy_config.py

### ISSUE THREAD

**Issue by JerieD** [hyperledger/indy-sdk#409]
I've successfully ran pip3 install indy-node-dev on Mac but am running into an error when trying to start nodes 

```
which -a generate_indy_pool_transactions
/usr/local/bin/generate_indy_pool_transactions
bc-computer:~ momi$ /usr/local/bin/generate_indy_pool_transactions --nodes 4 --clients 5 --nodeNum 1 2 3 4
Traceback (most recent call last):
  File "/usr/local/bin/generate_indy_pool_transactions", line 16, in <module>
    getTxnOrderedFields(), ConfigHelper, NodeConfigHelper)
  File "/usr/local/lib/python3.6/site-packages/plenum/common/test_network_setup.py", line 207, in bootstrapTestNodes
    for line in fileinput.input(['/etc/indy/indy_config.py'], inplace=True):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 337, in _readline
    os.rename(self._filename, self._backupfilename)
PermissionError: [Errno 13] Permission denied: '/etc/indy/indy_config.py' -> '/etc/indy/indy_config.py.bak'
```

The original error I got was that the file wasn't found:

> FileNotFoundError: [Errno 2] No such file or directory: '/etc/indy/indy_config.py' -> '/etc/indy/indy_config.py.bak'

So I touched the file which resulted in the permission denied error.
```
 touch /etc/indy/indy_config.py
touch: /etc/indy/indy_config.py: Permission denied
bc-computer:~ momi$ sudo touch /etc/indy/indy_config.py
```

I also tried to run the generate_indy_pool_transactions command as sudo

bc-computer:~ momi$ sudo touch /etc/indy/indy_config.py

but got this error, probably because I didn't have the indy_config.py file to begin with:
```
sudo generate_indy_pool_transactions --nodes 4 --clients 5 --nodeNum 1 2 3 4
Traceback (most recent call last):
  File "/usr/local/bin/generate_indy_pool_transactions", line 16, in <module>
    getTxnOrderedFields(), ConfigHelper, NodeConfigHelper)
  File "/usr/local/lib/python3.6/site-packages/plenum/common/test_network_setup.py", line 216, in bootstrapTestNodes
    config_helper_class, node_config_helper_class)
  File "/usr/local/lib/python3.6/site-packages/plenum/common/test_network_setup.py", line 84, in bootstrapTestNodesCore
    os.makedirs(config_helper.genesis_dir, exist_ok=True)
  File "/usr/local/lib/python3.6/site-packages/indy_common/config_helper.py", line 16, in genesis_dir
    os.path.join(self.config.GENESIS_DIR, self.config.NETWORK_NAME))
AttributeError: module 'indy_config.py' has no attribute 'GENESIS_DIR'
```

I think [this](https://github.com/hyperledger/indy-node/commit/2c37ce6fd4187d81db9a3e8771740fd0d8136631) is an attempt to resolve the problem of missing files.

Should I run any of the scripts from that commit? Will they run on MacOS (High Sierra)?

My environment is:
uname -msra
Darwin bc-computer.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

Please advise on any next steps I should take to get problem resolved and to start nodes.

Thanks

**Comment by vimmerru** [comment]
I suggest to ask this question in Hyperledger RocketChat #indy-node channel. indy-node-dev isn't artifact of Indy SDK. Also as i know Indy Node doesn't support Mac platform now.
