### ISSUE TITLE
Cargo build failing in windows

### ISSUE THREAD

**Issue by secretsayan** [hyperledger/indy-sdk#618]
**While running the "cargo build" in windows the build fails saying---**

`error: failed to run custom build command for `indy-crypto v0.1.6-dev-30`
process didn't exit successfully: `F:\Hyperledger Indy\git-code\indy-sdk\indy-sdk\libindy\target\debug\build\indy-crypto-7f8e44fb5ad897ae\build-script-build` (exit code: 101)
--- stdout
target=x86_64-pc-windows-msvc

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by vimmerru** [comment]
1. Do you follow all steps from https://github.com/hyperledger/indy-sdk/blob/master/doc/windows-build.md 2. You need yo run your build with RUST_BACKTRACE=1 and provide full logs

**Comment by secretsayan** [comment]
I have followed the mentioned documents ,  not sure why I am getting this error.

Here are the full logs with RUST_BACKTRACE=1 ---







```
F:\Hyperledger Indy\git-code\indy-sdk\indy-sdk\libindy>cargo build
   Compiling quote v0.3.15
   Compiling rustc-serialize v0.3.24
   Compiling serde v0.9.15
   Compiling utf8-ranges v1.0.0
   Compiling safemem v0.2.0
   Compiling indy v1.3.1 (file:///F:/Hyperledger%20Indy/git-code/indy-sdk/indy-sdk/libindy)
   Compiling lazy_static v0.2.9
   Compiling winapi v0.2.8
   Compiling indy-crypto v0.1.6-dev-30
   Compiling num-traits v0.1.40
   Compiling winapi-build v0.1.1
   Compiling amcl v0.1.2
   Compiling void v1.0.2
   Compiling nodrop v0.1.12
   Compiling toml v0.2.1
   Compiling itoa v0.3.4
   Compiling int_traits v0.1.1
   Compiling libc v0.2.33
   Compiling bitflags v0.9.1
   Compiling pkg-config v0.3.9
   Compiling byteorder v1.1.0
   Compiling serde v1.0.19
   Compiling fake-simd v0.1.2
   Compiling typenum v1.9.0
   Compiling cc v1.0.3
   Compiling linked-hash-map v0.4.2
   Compiling foreign-types v0.2.0
   Compiling vcpkg v0.2.2
   Compiling regex-syntax v0.4.1
   Compiling openssl v0.9.20
   Compiling log v0.3.8
   Compiling hex v0.2.0
   Compiling elastic-array-plus v0.9.1
   Compiling dtoa v0.4.2
   Compiling unicode-xid v0.0.4
   Compiling gcc v0.3.54
   Compiling etcommon-hexutil v0.2.3
   Compiling error-chain v0.10.0
   Compiling byte-tools v0.2.0
   Compiling num-complex v0.1.40
error: failed to run custom build command for `indy-crypto v0.1.6-dev-30`
process didn't exit successfully: `F:\Hyperledger Indy\git-code\indy-sdk\indy-sdk\libindy\target\debug\build\indy-crypto-7f8e44fb5ad897ae\build-script-build` (exit code: 101)
--- stdout
target=x86_64-pc-windows-msvc

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:576
   6: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:537
   7: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:497
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
  10: core::result::unwrap_failed<std::env::VarError>
             at C:\projects\rust\src\libcore\macros.rs:23
  11: core::result::Result<alloc::string::String, std::env::VarError>::unwrap<alloc::string::String,std::env::VarError>
             at C:\projects\rust\src\libcore\result.rs:782
  12: build_script_build::main
             at .\build.rs:12
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:479
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:458
  18: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:358
  19: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  20: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  24: BaseThreadInitThunk
  25: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `indy v1.3.1 (file:///F:/Hyperledger%20Indy/git-code/indy-sdk/indy-sdk/libindy)`
process didn't exit successfully: `F:\Hyperledger Indy\git-code\indy-sdk\indy-sdk\libindy\target\debug\build\indy-96068d118c83ab82\build-script-build` (exit code: 101)
--- stdout
target=x86_64-pc-windows-msvc

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:576
   6: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:537
   7: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:497
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
  10: core::result::unwrap_failed<std::env::VarError>
             at C:\projects\rust\src\libcore\macros.rs:23
  11: core::result::Result<alloc::string::String, std::env::VarError>::unwrap<alloc::string::String,std::env::VarError>
             at C:\projects\rust\src\libcore\result.rs:782
  12: build_script_build::main
             at .\build.rs:12
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:479
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:458
  18: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:358
  19: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  20: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  24: BaseThreadInitThunk
  25: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jovfer** [comment]
Sounds like we have missed step in Readme for Windows.
@secretsayan could you please also specify `INDY_CRYPTO_PREBUILT_DEPS_DIR` environment variable to same directory as `INDY_PREBUILT_DEPS_DIR` and try again?

**Comment by secretsayan** [comment]
@jovfer Thanks for your suggestions and but I am getting this now -

```
F:\Hyperledger Indy\git-code\indy-sdk\indy-sdk\libindy>cargo build
   Compiling unicode-xid v0.0.4
   Compiling serde v1.0.19
   Compiling log v0.3.8
   Compiling byte-tools v0.2.0
   Compiling vcpkg v0.2.2
   Compiling winapi-build v0.1.1
   Compiling indy-crypto v0.1.6-dev-30
   Compiling hex v0.2.0
   Compiling openssl v0.9.20
   Compiling regex-syntax v0.4.1
   Compiling indy v1.3.1 (file:///F:/Hyperledger%20Indy/git-code/indy-sdk/indy-sdk/libindy)
   Compiling toml v0.2.1
   Compiling etcommon-hexutil v0.2.3
   Compiling itoa v0.3.4
   Compiling num-traits v0.1.40
   Compiling utf8-ranges v1.0.0
   Compiling dtoa v0.4.2
   Compiling winapi v0.2.8
   Compiling amcl v0.1.2
   Compiling lazy_static v0.2.9
   Compiling linked-hash-map v0.4.2
   Compiling typenum v1.9.0
   Compiling bitflags v0.9.1
   Compiling safemem v0.2.0
   Compiling nodrop v0.1.12
   Compiling serde v0.9.15
   Compiling elastic-array-plus v0.9.1
   Compiling byteorder v1.1.0
   Compiling gcc v0.3.54
   Compiling fake-simd v0.1.2
   Compiling rustc-serialize v0.3.24
   Compiling quote v0.3.15
   Compiling cc v1.0.3
   Compiling libc v0.2.33
   Compiling void v1.0.2
   Compiling pkg-config v0.3.9
   Compiling foreign-types v0.2.0
   Compiling int_traits v0.1.1
   Compiling error-chain v0.10.0
   Compiling synom v0.11.3
   Compiling kernel32-sys v0.2.2
   Compiling num-integer v0.1.35
   Compiling serde_json v1.0.5
   Compiling lru-cache v0.1.1
   Compiling etcommon-rlp v0.2.3
   Compiling rmp v0.8.7
   Compiling base64 v0.6.0
   Compiling memchr v1.0.2
   Compiling rand v0.3.18
   Compiling num-complex v0.1.40
   Compiling unreachable v1.0.0
   Compiling openssl-sys v0.9.20
   Compiling libsqlcipher-sys v0.8.6
   Compiling libsodium-sys v0.0.14
   Compiling metadeps v1.1.2
   Compiling syn v0.11.11
error: linking with `link.exe` failed: exit code: 1318
  |
  = note: "F:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build0.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build1.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build10.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build11.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build12.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build13.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build14.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build15.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build2.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build3.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build4.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build5.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build6.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build7.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build8.rcgu.o" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.build_script_build9.rcgu.o" "/OUT:F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.exe" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\build\\openssl-sys-5dd94dd8da9c55db\\build_script_build-5dd94dd8da9c55db.crate.allocator.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\deps" "/LIBPATH:C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\deps\\libcc-991e14bcff494c2f.rlib" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\deps\\libvcpkg-572ff74db99ff312.rlib" "F:\\Hyperledger Indy\\git-code\\indy-sdk\\indy-sdk\\libindy\\target\\debug\\deps\\libpkg_config-594bc9c4b58bab82.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-1cce2a9d20ab1f24.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-65a4af75723cdd90.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-2e8655cc7305d65c.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-46a305d94fa2d1ac.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-af1f1cda65a920c9.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-46dfcbf8c4dcea26.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_unicode-239f9a431f378980.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-b754d68cb5d0aae4.rlib" "C:\\Users\\sa272015\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-2cbf590829e54572.rlib" "advapi32.lib" "ole32.lib" "oleaut32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: msvcrt.lib(thread_locale.obj) : fatal error LNK1318: Unexpected PDB error; RPC (23) '(0x000006BA)'


error: aborting due to previous error

   Compiling num-iter v0.1.34
error: Could not compile `openssl-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed


```

**Comment by vimmerru** [comment]
@secretsayan Are you sure that you use rust with MSVC runtime (not gnu)?

**Comment by secretsayan** [comment]
I am using MSVC 64bit...

**Comment by vimmerru** [comment]
@secretsayan We never saw this for multiple month and we have few developers and CI that perform daily builds on windows. Do you still experience this problem? 

I am closing the ticker, but if problem is still here you can re-open and we will try to investigate.
