### ISSUE TITLE
getting_started.py fails in indy_prover_store_credential 

### ISSUE THREAD

**Issue by srinivasanraghavan** [hyperledger/indy-sdk#675]
The nodes are set up with the docket compose .. And I am using the master branch

The line anoncreds.prover_store_credential(alice_wallet, None, transcript_cred_request_json,
                                            transcript_cred_request_metadata_json, authdecrypted_transcript_cred_json,
                                            faber_transcript_cred_def, None)

fails with the following exception

Traceback (most recent call last):
  File "/home/srinivasan/ide/pycharm-community-2018.1.1/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/srinivasan/ide/pycharm-community-2018.1.1/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/srinivasan/ide/pycharm-community-2018.1.1/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/srinivasan/ide/pycharm-community-2018.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/srinivasan/code/indy-sdk/samples/python/src/main.py", line 16, in <module>
    run_coroutine(main)
  File "/home/srinivasan/code/indy-sdk/samples/python/src/utils.py", line 45, in run_coroutine
    loop.run_until_complete(coroutine())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/srinivasan/code/indy-sdk/samples/python/src/main.py", line 8, in main
    await getting_started.run()
  File "/home/srinivasan/code/indy-sdk/samples/python/src/getting_started.py", line 243, in run
    faber_transcript_cred_def, None)
  File "/home/srinivasan/code/indy-sdk/samples/python/venv/lib/python3.5/site-packages/indy/anoncreds.py", line 618, in prover_store_credential
    prover_store_credential.cb)
  File "/usr/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
indy.error.IndyError: ErrorCode.CommonInvalidParam8

**Comment by ArthurManz** [comment]
Have you tried rebuilding your containers to include all latest changes? I just ran the python Jupyter book and did just worked fine.

```
docker rm $(docker ps -qa)
docker rmi $(docker images -qa)
docker-compose up
```

**Comment by burdettadam** [comment]
We are using Jira to track issues now, please use this [Jira IS-994 ticket](https://jira.hyperledger.org/browse/IS-994) for any further discussion.
