### ISSUE TITLE
Segmentation fault  when runnin node.js samples

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/indy-sdk#932]
I tried to run the node.js samples. It fails when creating the wallet. Same thing happened when running a java sample as well.

**Error running node.js**
"Sovrin Steward" -> Create wallet
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE

**Complete error log for node.js**
0 info it worked if it ends with ok
1 verbose cli [ '/home/pradeep/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli '/home/pradeep/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gettingstarted@1.0.0~prestart: gettingstarted@1.0.0
6 info lifecycle gettingstarted@1.0.0~start: gettingstarted@1.0.0
7 verbose lifecycle gettingstarted@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle gettingstarted@1.0.0~start: PATH: /home/pradeep/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pradeep/Downloads/indy-sdk-master/samples/n
odejs/node_modules/.bin:/home/pradeep/fabric-samples/bin:/home/pradeep/.nvm/versions/node/v8.9.4/bin:/home/pradeep/bin:/home/pradeep/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/go/bin:/home/pradeep/go/bin
9 verbose lifecycle gettingstarted@1.0.0~start: CWD: /home/pradeep/Downloads/indy-sdk-master/samples/nodejs
10 silly lifecycle gettingstarted@1.0.0~start: Args: [ '-c', 'node gettingStarted.js' ]
11 silly lifecycle gettingstarted@1.0.0~start: Returned: code: 139 signal: null
12 info lifecycle gettingstarted@1.0.0~start: Failed to exec start script
13 verbose stack Error: gettingstarted@1.0.0 start: `node gettingStarted.js`
13 verbose stack Exit status 139
13 verbose stack at EventEmitter.<anonymous> (/home/pradeep/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack at emitTwo (events.js:126:13)
13 verbose stack at EventEmitter.emit (events.js:214:7)
13 verbose stack at ChildProcess.<anonymous> (/home/pradeep/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at emitTwo (events.js:126:13)
13 verbose stack at ChildProcess.emit (events.js:214:7)
13 verbose stack at maybeClose (internal/child_process.js:925:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid gettingstarted@1.0.0
15 verbose cwd /home/pradeep/Downloads/indy-sdk-master/samples/nodejs
16 verbose Linux 4.15.0-24-generic
17 verbose argv "/home/pradeep/.nvm/versions/node/v8.9.4/bin/node" "/home/pradeep/.nvm/versions/node/v8.9.4/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm v5.6.0
20 error code ELIFECYCLE
21 error errno 139
22 error gettingstarted@1.0.0 start: `node gettingStarted.js`
22 error Exit status 139
23 error Failed at the gettingstarted@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 139, true ]
pradeep@pradeep-VirtualBox:~/Downloads/indy-sd

**Comment by pradeeppadmarajaiah** [comment]
Changed the node ip from 0.0.0.0 to 127.0.0.1.Able to run successfully with the fresh setup.
